"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { prisma } from "@/lib/prisma";
import { requerirRolEmpresaActiva as requerirRol } from "@/lib/empresas";
import { puedeRealizar } from "@/lib/permisos";
import { normalizarLineasAcuerdo, cantidadLiberable } from "@/lib/acuerdosSuministro";
import { crearFechaCalendarioLocal } from "@/lib/fechas";
import { siguienteNumeroAcuerdoSuministro, siguienteNumeroOrdenCompra } from "@/lib/correlativos";
import { pasosAplicablesCompra } from "@/lib/aprobacionesCompra";
import { obtenerConfiguracionEmpresa } from "@/lib/empresa";
export type EstadoAcuerdo={error?:string};
function parsear(cadena:string){try{return JSON.parse(cadena);}catch{return null;}}
export async function crearAcuerdo(_e:EstadoAcuerdo,fd:FormData):Promise<EstadoAcuerdo>{const auth=await requerirRol(["ALMACEN"]);if("error"in auth)return auth;if(!(await puedeRealizar(auth.usuario,"materiales","crear")))return{error:"No tiene permiso."};const proveedorId=String(fd.get("proveedorId")??"");const titulo=String(fd.get("titulo")??"").trim();const moneda=String(fd.get("moneda")??"PEN");const tipoCambio=moneda==="PEN"?1:Number(fd.get("tipoCambio"));const vigenteDesde=crearFechaCalendarioLocal(String(fd.get("vigenteDesde")??""));const vigenteHasta=crearFechaCalendarioLocal(String(fd.get("vigenteHasta")??""));const lineas=normalizarLineasAcuerdo(parsear(String(fd.get("lineas")??"[]")));if(!proveedorId||titulo.length<4||!["PEN","USD"].includes(moneda)||!Number.isFinite(tipoCambio)||tipoCambio<=0||!vigenteDesde||!vigenteHasta||vigenteHasta<vigenteDesde||!lineas?.length)return{error:"Complete proveedor, vigencia, moneda y líneas válidas."};let id="";try{await prisma.$transaction(async tx=>{const [p,c]=await Promise.all([tx.proveedor.count({where:{id:proveedorId,empresaId:auth.usuario.empresaId,activo:true}}),tx.insumo.count({where:{empresaId:auth.usuario.empresaId,activo:true,id:{in:lineas.map(l=>l.insumoId)}}})]);if(p!==1||c!==lineas.length)throw new Error("Proveedor o materiales fuera de la empresa activa.");const numero=await siguienteNumeroAcuerdoSuministro(tx,auth.usuario.empresaId);const a=await tx.acuerdoSuministro.create({data:{empresaId:auth.usuario.empresaId,numero,proveedorId,titulo,moneda,tipoCambio,vigenteDesde,vigenteHasta,usuarioId:auth.usuario.id,usuarioNombre:auth.usuario.nombre,lineas:{create:lineas}}});id=a.id;});}catch(e){return{error:e instanceof Error?e.message:"No se pudo crear."};}revalidatePath("/logistica/acuerdos-suministro");redirect(`/logistica/acuerdos-suministro/${id}`);}
export async function liberarAcuerdo(acuerdoId:string,_e:EstadoAcuerdo,fd:FormData):Promise<EstadoAcuerdo>{const auth=await requerirRol(["ALMACEN"]);if("error"in auth)return auth;if(!(await puedeRealizar(auth.usuario,"materiales","crear")))return{error:"No tiene permiso."};const cantidades=parsear(String(fd.get("cantidades")??"{}"));if(typeof cantidades!=="object"||cantidades===null)return{error:"Cantidades inválidas."};let ocId="";try{await prisma.$transaction(async tx=>{const a=await tx.acuerdoSuministro.findFirst({where:{id:acuerdoId,empresaId:auth.usuario.empresaId,estado:"ACTIVO",vigenteDesde:{lte:new Date()},vigenteHasta:{gte:new Date()}},include:{lineas:true}});if(!a)throw new Error("El acuerdo no está vigente.");const seleccion=a.lineas.map(l=>({linea:l,cantidad:Number((cantidades as Record<string,unknown>)[l.id])})).filter(x=>Number.isFinite(x.cantidad)&&x.cantidad>0);if(!seleccion.length||seleccion.some(x=>!cantidadLiberable(x.linea.cantidadComprometida.toNumber(),x.linea.cantidadLiberada.toNumber(),x.cantidad)))throw new Error("La liberación supera el saldo contractual.");for(const x of seleccion){const r=await tx.acuerdoSuministroLinea.updateMany({where:{id:x.linea.id,cantidadLiberada:x.linea.cantidadLiberada},data:{cantidadLiberada:{increment:x.cantidad}}});if(r.count!==1)throw new Error("El saldo contractual cambió; actualice e intente nuevamente.");}const total=seleccion.reduce((s,x)=>s+x.cantidad*x.linea.precioUnitario.toNumber(),0);const totalPen=a.moneda==="USD"?total*a.tipoCambio.toNumber():total;const config=await obtenerConfiguracionEmpresa(auth.usuario.empresaId,tx);const pasos=await pasosAplicablesCompra(tx,auth.usuario.empresaId,totalPen,config.montoAprobacionCompras.toNumber());const numero=await siguienteNumeroOrdenCompra(tx);const oc=await tx.ordenCompra.create({data:{empresaId:auth.usuario.empresaId,numero,proveedorId:a.proveedorId,acuerdoId:a.id,moneda:a.moneda,tipoCambio:a.tipoCambio,total,notas:`Liberación de ${a.numero}`,estadoAprobacion:pasos.length?"PENDIENTE":"NO_REQUERIDA",usuarioId:auth.usuario.id,usuarioNombre:auth.usuario.nombre,detalles:{create:seleccion.map(x=>({insumoId:x.linea.insumoId,acuerdoLineaId:x.linea.id,cantidad:x.cantidad,costoUnitario:x.linea.precioUnitario,subtotal:x.cantidad*x.linea.precioUnitario.toNumber(),fechaEntregaEsperada:a.vigenteHasta}))},pasosAprobacion:{create:pasos}}});const liberado=new Map(seleccion.map(x=>[x.linea.id,x.cantidad]));if(a.lineas.every(l=>l.cantidadLiberada.toNumber()+(liberado.get(l.id)??0)>=l.cantidadComprometida.toNumber()-1e-9))await tx.acuerdoSuministro.update({where:{id:a.id},data:{estado:"CERRADO"}});ocId=oc.id;});}catch(e){return{error:e instanceof Error?e.message:"No se pudo liberar."};}revalidatePath(`/logistica/acuerdos-suministro/${acuerdoId}`);revalidatePath("/logistica/ordenes-compra");redirect(`/logistica/ordenes-compra/${ocId}`);}
