ALTER TABLE "insumos" ADD COLUMN "plazoEntregaDias" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "insumos" ADD COLUMN "cantidadMinimaCompra" DECIMAL NOT NULL DEFAULT 0;
ALTER TABLE "insumos" ADD COLUMN "multiploCompra" DECIMAL NOT NULL DEFAULT 0;
