"use server";
import { revalidatePath } from "next/cache"; import { redirect } from "next/navigation"; import { prisma } from "@/lib/prisma"; import { requerirRol } from "@/lib/auth"; import { puedeRealizar } from "@/lib/permisos"; import { normalizarCaracteristicasPlan } from "@/lib/planesCalidad";
export type EstadoPlan={error?:string};

// Las características se copian campo por campo al crear, y no con el objeto
// entero que devuelve el normalizador. No es estilo: el normalizador lo
// comparten el plan de PRODUCTO y el de INSUMO, y cada campo que ganó para el
// producto —esDensidad, instrumentoId— llegaba acá y Prisma rechazaba el
// create con un campo que este modelo no tiene. Publicar un plan de insumos
// estuvo roto dos ciclos sin que nada lo avisara: TypeScript no revisa
// propiedades de más cuando se pasa una variable, y no había prueba.
//
// La marca de densidad NO se copia a propósito: la densidad de un insumo no
// gobierna ninguna conversión hoy, y agregarla sería inventar un requisito.
export async function crearPlanInsumo(_e:EstadoPlan,fd:FormData):Promise<EstadoPlan>{const auth=await requerirRol(["ALMACEN","PRODUCCION"]);if("error" in auth)return auth;if(!(await puedeRealizar(auth.usuario,"materiales","editar")))return{error:"No tiene permiso."};const insumoId=String(fd.get("insumoId")??"");const nombre=String(fd.get("nombre")??"").trim();try{const caracteristicas=normalizarCaracteristicasPlan(String(fd.get("caracteristicas")??""));await prisma.$transaction(async tx=>{const insumo=await tx.insumo.findFirst({where:{id:insumoId,empresaId:auth.usuario.empresaId,activo:true,requiereInspeccion:true}});if(!insumo)throw new Error("Seleccione un insumo activo que requiera inspección.");const instrumentos=[...new Set(caracteristicas.map(c=>c.instrumentoId).filter((x):x is string=>x!==null))];if(instrumentos.length>0){const propios=await tx.instrumentoMedicion.count({where:{id:{in:instrumentos},empresaId:auth.usuario.empresaId}});if(propios!==instrumentos.length)throw new Error("Algún instrumento no pertenece a la compañía activa.");}const ultima=await tx.planInspeccionInsumo.findFirst({where:{insumoId},orderBy:{version:"desc"}});const ahora=new Date();await tx.planInspeccionInsumo.updateMany({where:{insumoId,activo:true},data:{activo:false,vigenteHasta:ahora}});await tx.planInspeccionInsumo.create({data:{empresaId:auth.usuario.empresaId,insumoId,version:(ultima?.version??0)+1,nombre,vigenteDesde:ahora,usuarioId:auth.usuario.id,usuarioNombre:auth.usuario.nombre,caracteristicas:{create:caracteristicas.map(c=>({secuencia:c.secuencia,nombre:c.nombre,unidadMedida:c.unidadMedida,limiteInferior:c.limiteInferior,limiteSuperior:c.limiteSuperior,metodoEnsayo:c.metodoEnsayo,obligatoria:c.obligatoria,instrumentoId:c.instrumentoId}))}}});});}catch(e){return{error:e instanceof Error?e.message:"No se pudo publicar."};}revalidatePath("/logistica/inspeccion-compras");revalidatePath("/logistica/inspeccion-compras/planes");redirect("/logistica/inspeccion-compras/planes");}
