CREATE TABLE "planes_inspeccion_insumo" ("id" TEXT NOT NULL PRIMARY KEY,"empresaId" TEXT NOT NULL DEFAULT '1',"insumoId" TEXT NOT NULL,"version" INTEGER NOT NULL,"nombre" TEXT NOT NULL,"activo" BOOLEAN NOT NULL DEFAULT true,"vigenteDesde" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,"vigenteHasta" DATETIME,"usuarioId" TEXT NOT NULL,"usuarioNombre" TEXT NOT NULL,"creadoEn" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "planes_inspeccion_insumo_insumoId_fkey" FOREIGN KEY ("insumoId") REFERENCES "insumos"("id") ON DELETE RESTRICT ON UPDATE CASCADE);
CREATE UNIQUE INDEX "planes_inspeccion_insumo_insumoId_version_key" ON "planes_inspeccion_insumo"("insumoId","version");
CREATE INDEX "planes_inspeccion_insumo_empresaId_activo_idx" ON "planes_inspeccion_insumo"("empresaId","activo");
CREATE TABLE "caracteristicas_plan_insumo" ("id" TEXT NOT NULL PRIMARY KEY,"planId" TEXT NOT NULL,"secuencia" INTEGER NOT NULL,"nombre" TEXT NOT NULL,"unidadMedida" TEXT NOT NULL,"limiteInferior" DECIMAL,"limiteSuperior" DECIMAL,"metodoEnsayo" TEXT,"obligatoria" BOOLEAN NOT NULL DEFAULT true,CONSTRAINT "caracteristicas_plan_insumo_planId_fkey" FOREIGN KEY ("planId") REFERENCES "planes_inspeccion_insumo"("id") ON DELETE CASCADE ON UPDATE CASCADE);
CREATE UNIQUE INDEX "caracteristicas_plan_insumo_planId_secuencia_key" ON "caracteristicas_plan_insumo"("planId","secuencia");
ALTER TABLE "inspecciones_compra" ADD COLUMN "planInspeccionId" TEXT REFERENCES "planes_inspeccion_insumo"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "inspecciones_compra" ADD COLUMN "planVersion" INTEGER;
CREATE TABLE "mediciones_inspeccion_compra" ("id" TEXT NOT NULL PRIMARY KEY,"inspeccionCompraId" TEXT NOT NULL,"secuencia" INTEGER NOT NULL,"nombre" TEXT NOT NULL,"unidadMedida" TEXT NOT NULL,"limiteInferior" DECIMAL,"limiteSuperior" DECIMAL,"metodoEnsayo" TEXT,"valorMedido" DECIMAL NOT NULL,"conforme" BOOLEAN NOT NULL,CONSTRAINT "mediciones_inspeccion_compra_inspeccionCompraId_fkey" FOREIGN KEY ("inspeccionCompraId") REFERENCES "inspecciones_compra"("id") ON DELETE CASCADE ON UPDATE CASCADE);
CREATE UNIQUE INDEX "mediciones_inspeccion_compra_inspeccionCompraId_secuencia_key" ON "mediciones_inspeccion_compra"("inspeccionCompraId","secuencia");
